export const sections = [
  {
    id: 'access',
    title: 'Acceso y circulación',
    items: [
      ['access-01', 'Ruta accesible y transitable hasta el ingreso', 'Comprobar continuidad del recorrido accesible desde el exterior y ausencia de obstáculos.', 'Anexo VII · pp. 3 y 10'],
      ['access-02', 'Ingreso con rampa cuando exista desnivel', 'El acceso al edificio debe disponer de rampa cuando sea necesaria para salvar desniveles.', 'Anexo VII · p. 3'],
      ['access-03', 'Pasillos generales ≥ 1.20 m', 'Verificar un ancho mínimo de 1.20 m para pasillos.', 'Anexo VII · p. 3'],
      ['access-04', 'Giro de hasta 90°: ancho ≥ 1.00 m', 'En giros de hasta 90° comprobar un ancho mínimo de 1.00 m.', 'Anexo VII · p. 3'],
      ['access-05', 'Giro mayor de 90°: ancho ≥ 1.20 m', 'En giros mayores de 90° comprobar un ancho mínimo de 1.20 m.', 'Anexo VII · p. 3'],
      ['access-06', 'Cruce frecuente de dos sillas: ancho ≥ 1.50 m', 'Cuando exista circulación frecuente de dos sillas de ruedas, verificar 1.50 m de ancho mínimo.', 'Anexo VII · p. 3'],
      ['access-07', 'Área accesible de espera ≥ 1.20 × 1.20 m', 'En espacios de estar y salas de espera, reservar y señalizar un área mínima de 1.20 × 1.20 m.', 'Anexo VII · p. 3'],
    ],
  },
  {
    id: 'ramps',
    title: 'Rampas',
    items: [
      ['ramp-01', 'Ancho mínimo de rampa ≥ 0.90 m', 'Comprobar 0.90 m de ancho mínimo.', 'Anexo VII · p. 3'],
      ['ramp-02', 'Descansos ≥ 1.20 m', 'Verificar descansos con dimensión mínima de 1.20 m.', 'Anexo VII · p. 3'],
      ['ramp-03', 'Inicio y final con espacio de giro Ø 1.20 m', 'Al inicio y al final de la rampa debe poder inscribirse un círculo mínimo de 1.20 m de diámetro.', 'Anexo VII · p. 3'],
      ['ramp-04', 'Pendiente ≤ 6% para tramos de 10 a 15 m', 'Aplicar la pendiente máxima indicada para tramos rectos entre descansos.', 'Anexo VII · p. 3'],
      ['ramp-05', 'Pendiente ≤ 8% para tramos de 3 a 10 m', 'Aplicar la pendiente máxima indicada para tramos rectos entre descansos.', 'Anexo VII · p. 3'],
      ['ramp-06', 'Pendiente ≤ 10% para tramos de 1.50 a 3 m', 'Aplicar la pendiente máxima indicada para tramos rectos entre descansos.', 'Anexo VII · p. 3'],
      ['ramp-07', 'Pendiente ≤ 12% para tramos de hasta 1.50 m', 'Aplicar la pendiente máxima indicada para tramos rectos entre descansos.', 'Anexo VII · p. 3'],
      ['ramp-08', 'Doble circulación con pasamanos central', 'Cuando exista doble circulación, verificar pasamanos intermedio central.', 'Anexo VII · p. 3'],
    ],
  },
  {
    id: 'stairs',
    title: 'Escaleras y pasamanos',
    items: [
      ['stairs-01', 'Huella con borde o arista redondeada', 'Revisar la geometría del borde de cada peldaño.', 'Anexo VII · p. 3'],
      ['stairs-02', 'Encuentro huella–contrahuella a 90°', 'Evitar resaltes o discontinuidades entre huella y contrahuella.', 'Anexo VII · pp. 3 y 21'],
      ['stairs-03', 'Huella ≥ 28 cm', 'El ejemplo gráfico indica que la dimensión de la huella no debe ser menor a 28 cm.', 'Anexo VII · p. 21 · ejemplo gráfico'],
      ['stairs-04', 'Máximo 18 peldaños consecutivos', 'Comprobar el máximo mostrado en el esquema gráfico.', 'Anexo VII · p. 21 · ejemplo gráfico'],
      ['stairs-05', 'Pasamanos a 0.90 m y continuos', 'Los pasamanos en rampas y escaleras deben ser continuos en todo el recorrido, incluido el descanso.', 'Anexo VII · pp. 3 y 20'],
      ['stairs-06', 'Agarre circular aprox. Ø 3–5 cm', 'Verificar sección circular de agarre, fijación firme y extremos curvados.', 'Anexo VII · pp. 3 y 21'],
      ['stairs-07', 'Separación del pasamanos a obstáculos ≥ 4 cm', 'Dejar separación suficiente respecto a muro u obstáculos.', 'Anexo VII · p. 21'],
      ['stairs-08', 'Pavimento señalizador al inicio y final', 'Verificar la franja señalizadora mostrada en el esquema de escalera.', 'Anexo VII · p. 21 · ejemplo gráfico'],
    ],
  },
  {
    id: 'doors',
    title: 'Puertas y ventanas',
    items: [
      ['doors-01', 'Puertas con ancho libre ≥ 0.80 m', 'Verificar el ancho mínimo indicado para puertas.', 'Anexo VII · p. 4'],
      ['doors-02', 'Puerta alternativa si existe puerta giratoria', 'Las puertas giratorias no se consideran aptas para personas con discapacidad; debe existir alternativa de entrada.', 'Anexo VII · p. 4'],
      ['doors-03', 'Puertas correderas con rodamiento adecuado', 'Comprobar un mecanismo de desplazamiento apropiado.', 'Anexo VII · p. 4'],
      ['doors-04', 'Manillas no circulares', 'Revisar que las agarraderas/manillas puedan accionarse con facilidad.', 'Anexo VII · pp. 4 y 22'],
      ['doors-05', 'Antepecho de ventana ≤ 0.85 m cuando corresponda', 'Revisar antepechos y visibilidad para usuario en silla de ruedas.', 'Anexo VII · pp. 4 y 22'],
      ['doors-06', 'Puertas de emergencia señalizadas', 'Toda puerta de emergencia debe estar debidamente señalizada.', 'Anexo VII · p. 5'],
    ],
  },
  {
    id: 'elevator',
    title: 'Ascensor — si existe',
    items: [
      ['elevator-01', 'Cabina libre mínima 0.90 × 1.20 m', 'Comprobar las dimensiones mínimas interiores de la cabina.', 'Anexo VII · p. 4'],
      ['elevator-02', 'Altura interior mínima 2.10 m', 'Verificar la altura libre mínima de cabina.', 'Anexo VII · p. 4'],
      ['elevator-03', 'Tablero interior entre 0.90 y 1.20 m', 'Comprobar la altura de los controles interiores.', 'Anexo VII · p. 4'],
      ['elevator-04', 'Botonera exterior entre 0.90 y 1.20 m', 'Comprobar la altura del botón de llamada exterior.', 'Anexo VII · p. 4'],
      ['elevator-05', 'Botones en alto relieve y equivalente en Braille', 'Revisar identificación táctil de pulsadores interiores y exteriores.', 'Anexo VII · p. 4'],
      ['elevator-06', 'Piso de cabina antideslizante', 'Verificar material de piso antideslizante.', 'Anexo VII · p. 4'],
    ],
  },
  {
    id: 'bathrooms',
    title: 'Área higiénica sanitaria',
    items: [
      ['bath-01', 'Puerta abatible o corredera ≥ 0.80 m', 'Verificar ancho mínimo y facilidad de acceso al recinto.', 'Anexo VII · p. 4'],
      ['bath-02', 'Espacio de maniobra y transferencia suficiente', 'Comparar la distribución con los esquemas de referencia para usuario en silla de ruedas.', 'Anexo VII · pp. 23 y 25 · ejemplos gráficos'],
      ['bath-03', 'Asiento de inodoro entre 0.40 y 0.45 m', 'Comprobar altura del asiento terminado.', 'Anexo VII · p. 4'],
      ['bath-04', 'Barras de apoyo a ambos lados del inodoro', 'Debe existir apoyo lateral a ambos lados.', 'Anexo VII · p. 4'],
      ['bath-05', 'Al menos una barra lateral abatible', 'Verificar barra abatible según disposición del inodoro.', 'Anexo VII · p. 4'],
      ['bath-06', 'Barras Ø 3.5–5 cm y separadas 5 cm del muro', 'Comprobar sección, separación y fijación firme.', 'Anexo VII · pp. 4 y 23'],
      ['bath-07', 'Lavamanos sin pedestal a 0.80 m', 'Permitir aproximación frontal u oblicua de silla de ruedas.', 'Anexo VII · pp. 4 y 24'],
      ['bath-08', 'Grifería de palanca o monomando', 'Evitar griferías de difícil agarre o giro.', 'Anexo VII · pp. 4 y 24'],
      ['bath-09', 'Borde inferior de espejo a 0.90 m', 'Verificar altura accesible del espejo.', 'Anexo VII · pp. 4 y 24'],
      ['bath-10', 'Accesorios entre 0.70 y 1.20 m', 'Comprobar dispensadores y accesorios de uso habitual.', 'Anexo VII · p. 4'],
      ['bath-11', 'Urinario adulto a 0.60 m — si existe', 'El Anexo indica 0.40 m para niños y 0.60 m para adultos.', 'Anexo VII · pp. 4 y 24'],
      ['bath-12', 'Piso homogéneo y antideslizante en seco y mojado', 'Verificar acabado continuo y seguro.', 'Anexo VII · pp. 4 y 13'],
      ['bath-13', 'Iluminación automática vinculada al cierre de puerta', 'Comprobar el sistema de encendido y apagado indicado.', 'Anexo VII · p. 4'],
    ],
  },
  {
    id: 'services',
    title: 'Servicios, evacuación y emergencia',
    items: [
      ['service-01', 'Pulsadores, interruptores, timbres y alarmas entre 0.90 y 1.00 m', 'Incluye botoneras, zumbadores, porteros electrónicos y elementos análogos.', 'Anexo VII · p. 5'],
      ['service-02', 'Ducto de basura ≤ 1.00 m — si existe', 'El acceso al ducto debe quedar al ras del muro y dentro de la altura máxima indicada.', 'Anexo VII · p. 5'],
      ['service-03', 'Detección de incendio perceptible por personas con discapacidad', 'Revisar que equipos e instalaciones permitan la percepción de la alarma.', 'Anexo VII · p. 5'],
      ['service-04', 'Adaptaciones y servicios de accesibilidad señalizados', 'Toda adecuación o servicio accesible debe estar debidamente señalizado.', 'Anexo VII · p. 5'],
    ],
  },
  {
    id: 'dining',
    title: 'Comedor — si existe',
    items: [
      ['dining-01', 'Al menos una mesa accesible para silla de ruedas', 'En lugares de consumo de alimentos debe existir una mesa cuya superficie permita el acercamiento de una silla de ruedas.', 'Anexo VII · p. 5'],
    ],
  },
  {
    id: 'outside',
    title: 'Recorridos exteriores',
    items: [
      ['outside-01', 'Franja libre peatonal sin obstáculos', 'Mantener libre de obstáculos, salientes y mobiliario urbano la franja de circulación.', 'Anexo VII · pp. 10 y 27'],
      ['outside-02', 'Pavimento firme, homogéneo y antideslizante', 'Verificar continuidad y seguridad de las superficies exteriores.', 'Anexo VII · p. 10'],
      ['outside-03', 'Rejillas y tapas al mismo nivel del piso', 'Deben quedar ancladas y niveladas, incluso en rampas o superficies inclinadas.', 'Anexo VII · p. 10'],
      ['outside-04', 'Paso peatonal con rampa ≤ 8% y ancho ≥ 1.20 m', 'Comprobar pendiente y ancho de cruce accesible.', 'Anexo VII · pp. 10 y 27'],
      ['outside-05', 'Tiras táctiles para orientar y advertir', 'Utilizar pavimento táctil para indicar recorridos, obstáculos y cambios de nivel.', 'Anexo VII · pp. 10 y 13'],
      ['outside-06', 'Mobiliario urbano fuera del recorrido peatonal', 'El mobiliario no debe constituir impedimento para el peatón.', 'Anexo VII · p. 10'],
    ],
  },
  {
    id: 'parking',
    title: 'Parqueos accesibles — si existen',
    items: [
      ['parking-01', 'Reserva permanente para vehículos de personas con discapacidad', 'El Anexo exige disponer de una reserva permanente.', 'Anexo VII · p. 10'],
      ['parking-02', 'Pavimento nivelado, firme y antideslizante', 'Comprobar las condiciones del área de estacionamiento accesible.', 'Anexo VII · p. 10'],
      ['parking-03', 'Señalización horizontal y vertical', 'Verificar señalización completa de la plaza accesible.', 'Anexo VII · pp. 10 y 29'],
      ['parking-04', 'Plaza perpendicular/oblicua: 3.50 × 5.00 m', 'Comprobar ancho y largo indicados.', 'Anexo VII · p. 10'],
      ['parking-05', 'Plaza paralela: 3.50 × 6.50 m', 'Comprobar ancho y largo indicados.', 'Anexo VII · p. 10'],
    ],
  },
  {
    id: 'signals',
    title: 'Texturas, contraste y señalización',
    items: [
      ['signals-01', 'Contraste visual en puertas, pasamanos, escaleras, baños, salidas y desniveles', 'Usar colores de contraste para destacar elementos relevantes del recorrido.', 'Anexo VII · p. 13'],
      ['signals-02', 'Pisos sin relieve, estables y antideslizantes', 'Revisar comportamiento tanto en seco como en mojado.', 'Anexo VII · p. 13'],
      ['signals-03', 'Franjas señalizadoras en obstáculos, cambios de sentido, escaleras, rampas y desniveles', 'Comprobar señalización táctil/visual del pavimento.', 'Anexo VII · p. 13'],
      ['signals-04', 'Señales orientadoras, direccionales y funcionales donde correspondan', 'Revisar ubicación lógica, visible y comprensible de la información.', 'Anexo VII · p. 15'],
      ['signals-05', 'Señalización táctil entre 0.70 y 1.20 m', 'Las señales táctiles deben presentar relieve contrastado y no lacerante.', 'Anexo VII · p. 15'],
      ['signals-06', 'Tamaño de señal según A = L² / 2000', 'Aplicar la fórmula indicada para distancias de lectura menores de 50 m.', 'Anexo VII · p. 15'],
      ['signals-07', 'Símbolos internacionales de accesibilidad correctamente utilizados', 'Revisar simbología de silla de ruedas, sordera/hipoacusia y deficiencia visual cuando corresponda.', 'Anexo VII · pp. 15–16'],
    ],
  },
]

export const allItems = sections.flatMap((section) => section.items.map(([id, title, detail, source]) => ({
  id,
  sectionId: section.id,
  sectionTitle: section.title,
  title,
  detail,
  source,
})))
